### ISSUE TITLE
unexpected upper() called in to_checksum_address(address)

### ISSUE THREAD

**Issue by hbprotoss** [ethereum/eth-utils#91]
https://github.com/ethereum/eth-utils/blob/c06d26119cd8062cf4e75d87a620c2d5892151ee/eth_utils/address.py#L118

norm_address[i] should not invoke `upper()`. 

In that case, address is '0x8eb009288b68c343de5bc393a7e13c28f5425780', checksum_address is '0x8EB009288b68C343DE5Bc393a7e13C28F5425780'. 

`is_checksum_address(value)` returns `False`. The two addresses should be compared case-insensitively, although unnecessary

**Comment by pipermerriam** [comment]
Again, this is not a bug.

The plain address is  `0x8eb009288b68c343de5bc393a7e13c28f5425780`

The checksummed address is `0x8EB009288b68C343DE5Bc393a7e13C28F5425780`

Note the mixed case of the checksummed address.  The casing differences encode the checksum for the address.

The function `to_checksum_address` takes an address and returns the checksummed values.  The `upper()` call you link to is how it encodes the checksum in the return value.

The function `is_checksum_address` takes an address and returns `True` or `False` indicating whether it contains a valid checksum.  The comparison I think you are referencing **must** be case sensitive, otherwise it would return `True` for non-checksummed addresses.

**Comment by hbprotoss** [comment]
@pipermerriam So `0x8eb009288b68c343de5bc393a7e13c28f5425780` is an invalid address?

**Comment by hbprotoss** [comment]
And all addresses passed to web3.py must be checksummed address?

**Comment by carver** [comment]
> And all addresses passed to web3.py must be checksummed address?

Yes
